DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255)
, AUTHOR_ID BIGINT REFERENCES AUTHORS(ID)
, GENRE_ID BIGINT REFERENCES  GENRES(ID));

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, COMMENT VARCHAR(255), BOOK_ID BIGINT);